Repository zzalmyu/zzalmyu-frontend, pull requests merged in 2024-09, with the labels that each got.

#255 [#254] Modify: query factory 수정
  src/hooks/api/auth/queryKeyFactories.ts
  src/hooks/api/chat/queryKeyFactories.ts
  src/hooks/api/report/queryKeyFactories.ts
  src/hooks/api/tag/queryKeyFactories.ts
  src/hooks/api/zzal/queryKeyFactories.ts
Labels: ✏️ Modify

#259 Bugfix: tanstack/router 관련 파일 주석 처리
  src/routes/-NotFound.tsx
  src/routes/__root.tsx
  src/routes/_authentication.tsx
  src/routes/_authentication/admin/reports/$imageId/route.lazy.tsx
  src/routes/_authentication/admin/reports/$imageId/route.tsx
  src/routes/_authentication/admin/reports/route.lazy.tsx
  src/routes/_authentication/admin/reports/route.tsx
  src/routes/_authentication/delete-account/route.lazy.tsx
  src/routes/_authentication/delete-account/route.tsx
  src/routes/_authentication/upload-zzal/route.lazy.tsx
  src/routes/_authentication/upload-zzal/route.tsx
  src/routes/_layout-with-chat.tsx
  src/routes/_layout-with-chat/index.route.lazy.tsx
  src/routes/_layout-with-chat/index.route.tsx
  src/routes/_layout-with-chat/my-liked-zzals/route.lazy.tsx
  src/routes/_layout-with-chat/my-liked-zzals/route.tsx
  src/routes/_layout-with-chat/my-uploaded-zzals/route.lazy.tsx
  src/routes/_layout-with-chat/my-uploaded-zzals/route.tsx
Labels: 🐞 Bugfix

#260 [#257] Package: MSW 설치 및 세팅 + 로그인을 제외한 기존 API mocking 핸들러 구현
  package.json
  pnpm-lock.yaml
  public/mockServiceWorker.js
  src/app/layout.tsx
  src/components/MswProvider.tsx
  src/mocks/browser.ts
  src/mocks/data/chats.ts
  src/mocks/data/reports.ts
  src/mocks/data/tags.ts
  src/mocks/data/zzals.ts
  src/mocks/handlers/chatHandlers.ts
  src/mocks/handlers/index.ts
  src/mocks/handlers/reportHandlers.ts
  src/mocks/handlers/tagHandlers.ts
  src/mocks/handlers/zzalHandlers.ts
  src/mocks/server.ts
Labels: 📦️ package

#262 [#261] Fix: 서버에서 localStorage 인식 안됨 버그 해결
  src/utils/localStorage.ts
Labels: 🐞 Bugfix

#265 [#264] Fix: 구현되지 않은 authHandler를 import 함으로써 생기는 버그 수정
  src/mocks/handlers/index.ts
Labels: 🐞 Bugfix

#263 [#256] Feat: 쿼리 팩토리 적용 및 네트워크 워터폴 최적화
  src/app/(with_chat)/home/Home.tsx
  src/app/(with_chat)/home/page.tsx
  src/app/(with_chat)/my-liked-zzals/MyLikedZzals.tsx
  src/app/(with_chat)/my-liked-zzals/page.tsx
  src/app/(with_chat)/my-uploaded-zzals/MyUploadedZzals.tsx
  src/app/(with_chat)/my-uploaded-zzals/page.tsx
  src/components/ImageDetailModal/index.tsx
  src/components/common/ZzalCard.tsx
  src/hooks/api/auth/useGetUserInformation.ts
  src/hooks/api/chat/useGetChat.ts
  src/hooks/api/report/useGetReportDetails.ts
  src/hooks/api/report/useGetReports.ts
  src/hooks/api/tag/useGetPopularTags.ts
  src/hooks/api/tag/useGetTags.ts
  src/hooks/api/tag/useGetTopTagsFromHome.ts
  src/hooks/api/tag/useGetTopTagsFromLiked.ts
  src/hooks/api/tag/useGetTopTagsFromUploaded.ts
  src/hooks/api/zzal/useAddImageLike.ts
  src/hooks/api/zzal/useGetMyUploadedZzals.ts
  src/hooks/api/zzal/useRemoveImageLike.ts
  src/types/zzal.ts
Labels: ✨ Feature
