Repository zzalmyu/zzalmyu-frontend, pull requests merged in 2024-02, with the labels that each got.

#2 [#1] Chore: 프로젝트 세팅
  .eslintrc.cjs
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/custom.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull_request_template.md
  .gitignore
  .husky/commit-msg
  .husky/pre-commit
  .nvmrc
  .prettierrc
  README.md
  commitlint.config.cjs
  index.html
  package.json
  pnpm-lock.yaml
  postcss.config.js
  prettier.config.js
  src/App.tsx
  src/components/.empty
  src/index.css
  src/main.tsx
  src/pages/.empty
  src/store/.empty
  src/types/.empty
  src/utils/tailwind.ts
  src/vite-env.d.ts
  tailwind.config.js
  tsconfig.json
  tsconfig.node.json
  vite.config.ts
Labels: ⚙ Chore

#7 [#5] Feat: 프로젝트 색상 토큰 설정
  index.html
  src/App.tsx
  tailwind.config.js
Labels: ✨ Feature

#15 [#4] Feat: 각 페이지별 라우팅 구현
  .eslintrc.cjs
  .prettierignore
  package.json
  pnpm-lock.yaml
  react-router.d.ts
  src/App.tsx
  src/hooks/.empty
  src/main.tsx
  src/pages/.empty
  src/routeTree.gen.ts
  src/routes/-NotFound.tsx
  src/routes/__root.tsx
  src/routes/admin/index.tsx
  src/routes/index.tsx
  src/routes/my-liked-zzal/index.tsx
  src/routes/my-uploaded-zzal/index.tsx
  src/routes/upload-zzal/index.tsx
  tsr.config.json
  vite.config.ts
Labels: ✨ Feature

#18 [#14] Chore: ESLint와 Prettier 패키지 설치 및 설정 업데이트
  .eslintrc.cjs
  .prettierrc
  package.json
  pnpm-lock.yaml
Labels: 📦️ package

#22 [#12] Feat: 공통 이미지 컴포넌트 구현
  package.json
  pnpm-lock.yaml
  src/components/common/ZzalCard.tsx
  tailwind.config.js
Labels: ✨ Feature

#29 [#28] Chore: pxr 단위 구현 및 적용
  tailwind.config.js
Labels: ⚙ Chore

#24 [#3] Feat: api core 추상화 함수 구현
  package.json
  pnpm-lock.yaml
  src/apis/core.ts
  src/utils/localStorage.ts
Labels: ✨ Feature

#19 [#8] Feat: 로그인 모달 UI 구현
  src/App.tsx
  src/assets/svg/google-login-btn.svg
  src/assets/svg/kakao-login-btn.svg
  src/assets/svg/naver-login-btn.svg
  src/components/LoginModal.tsx
  src/components/common/modals/Modal.tsx
  src/components/common/modals/ModalBody.tsx
  src/components/common/modals/ModalFooter.tsx
  src/components/common/modals/ModalHeader.tsx
  src/components/common/modals/ModalProvider.tsx
  src/hooks/modals/useModalContext.ts
  src/index.css
  src/routes/index.tsx
  tailwind.config.js
Labels: ✨ Feature

#31 [#26] Feat: 태그 검색 컴포넌트 구현
  .eslintrc.cjs
  package.json
  pnpm-lock.yaml
  src/components/common/RecommendTag.tsx
  src/components/common/TagBadge.tsx
  src/components/common/TagSearchForm.tsx
  src/constants/tag.ts
  src/store/.empty
  src/store/tag.ts
Labels: ✨ Feature

#27 [#10] Feat: ReportedImageList UI 구현
  src/components/.empty
  src/components/Admin/ReportedImageList.tsx
  src/routes/admin/index.tsx
  tailwind.config.js
Labels: ✨ Feature

#30 [#20] Feat: Alert 공통 컴포넌트 구현
  src/App.tsx
  src/components/common/DeleteConfirmModal.tsx
  src/routes/index.tsx
Labels: ✨ Feature

#42 [#41] Chore: prettier recommended 제거
  .eslintrc.cjs
  package.json
  pnpm-lock.yaml
  prettier.config.js
Labels: ⚙ Chore

#40 [#39] Fix: 공통 컴포넌트(ZzalCard)의 props 수정
  src/components/common/ZzalCard.tsx
Labels: ✏️ Modify

#33 [#21] Feat: 짤 업로드 페이지 UI 구현
  src/components/UploadZzal/ImageUpload.tsx
  src/components/UploadZzal/UploadGuide.tsx
  src/routes/upload-zzal/index.tsx
Labels: ✨ Feature

#35 [#25] Feat: 이미지 상세보기 모달 UI 구현
  src/components/ImageDetailModal/ImageMenuBar.tsx
  src/components/ImageDetailModal/TagNavigator.tsx
  src/components/ImageDetailModal/index.tsx
  src/components/common/modals/Modal.tsx
  src/routes/index.tsx
Labels: ✨ Feature

#49 [#48] Fix: 드롭다운 메뉴 동작 및 버튼 색상 버그 수정
  src/components/common/Header/DropdownMenu.tsx
Labels: 🐞 Bugfix

#53 [#52] Feat: 태그 '검색 결과가 없음'을 나타내는 컴포넌트 구현
  src/components/common/NoSearchResults.tsx
Labels: ✨ Feature

#55 [#51] Feat: useIntersectionObserver 훅 구현
  src/hooks/common/useIntersectionObserver.ts
Labels: ✨ Feature

#61 [#60] Fix: 태그 검색 시 자동완성 UI에 포커싱되어 검색창의 포커싱이 풀리는 버그 수정
  src/components/common/TagAutoComplete.tsx
  src/types/tag.dto.ts
  src/types/tag.ts
Labels: 🐞 Bugfix

#47 [#43] Feat: 관리자 이미지 상세 모달 페이지화
  src/components/Admin/ReportModal.tsx
  src/components/Admin/ReportedImageList.tsx
  src/components/AdminReports/ReportsTableBody .tsx
  src/components/AdminReportsDetail/ReportDetailTableBody.tsx
  src/components/common/admin/ReportTableHead.tsx
  src/routeTree.gen.ts
  src/routes/admin/index.tsx
  src/routes/admin/reports/$id/index.tsx
  src/routes/admin/reports/index.tsx
  src/types/report.dto.ts
  src/types/report.ts
Labels: ✨ Feature

#58 [#38] Feat: 채팅 UI 및 인터랙션 구현
  src/components/common/Chat/ChatPeek.tsx
  src/components/common/Chat/ChatSection.tsx
  src/components/common/Chat/ChatSendButton.tsx
  src/components/common/Chat/ChatToggleButton.tsx
  src/components/common/Chat/Message.tsx
  src/components/common/Chat/MessagePeek.tsx
  src/components/common/Chat/MessagePreview.tsx
  src/components/common/Chat/index.tsx
  src/routes/_layout-with-chat.tsx
  src/routes/_layout-with-chat/index.tsx
  src/store/chat.ts
  src/utils/sessionStorage.ts
Labels: ✨ Feature

#50 [#36] Feat: 채팅 레이아웃 및 토글 버튼 구현
  src/components/common/Chat/ChatPeek.tsx
  src/components/common/Chat/ChatSection.tsx
  src/components/common/Chat/ChatSendButton.tsx
  src/components/common/Chat/Message.tsx
  src/components/common/Chat/MessagePeek.tsx
  src/components/common/Chat/MessagePreview.tsx
  src/components/common/Chat/index.tsx
  src/index.css
  src/routeTree.gen.ts
  src/routes/__root.tsx
  src/routes/_layout-with-chat.tsx
  src/routes/_layout-with-chat/index.tsx
  src/routes/_layout-with-chat/my-liked-zzal/index.tsx
  src/routes/_layout-with-chat/my-uploaded-zzal/index.tsx
  src/routes/index.tsx
  src/store/chat.ts
  src/utils/sessionStorage.ts
Labels: ✨ Feature

#71 [#70] Chore: github actions workflow 작성
  .github/workflows/deploy.yml
Labels: ⚙ Chore

#67 [#62] 관리자 페이지 API 통합 및 기능 구현
  src/apis/report.ts
  src/components/AdminReports/ReportsTableBody .tsx
  src/components/AdminReportsDetail/ReportDetailsTableBody.tsx
  src/components/common/admin/ReportTableHead.tsx
  src/constants/api.ts
  src/hooks/api/report/useDeleteReportedImage.tsx
  src/hooks/api/report/useGetReportDetails.ts
  src/hooks/api/report/useGetReports.ts
  src/routeTree.gen.ts
  src/routes/__root.tsx
  src/routes/admin/reports/$id/index.tsx
  src/routes/admin/reports/$imageId/index.tsx
  src/routes/admin/reports/AdminReports.pendingComponent.tsx
  src/routes/admin/reports/index.tsx
  src/types/report.dto.ts
  src/types/report.ts
  src/utils/formatDate.ts
Labels: ✨ Feature

#78 [#77] Modify: 기존 assets 디렉토리 삭제후 s3 동기화
  .github/workflows/deploy.yml
Labels: 🐞 Bugfix
