Repository zzalmyu/zzalmyu-frontend, pull requests merged in 2024-03, with the labels that each got.

#66 [#64] Modify: TagSearchForm의 자식 요소로 TagAutoComplete 컴포넌트 병합
  .eslintrc.cjs
  .github/CODEOWNERS
  package.json
  pnpm-lock.yaml
  src/apis/tag.ts
  src/components/common/SearchTag/TagAutoComplete.tsx
  src/components/common/SearchTag/TagSearchForm.tsx
  src/components/common/TagAutoComplete.tsx
  src/hooks/api/tag/useGetTags.ts
  src/utils/debounce.ts
Labels: ✏️ Modify

#72 [#63] Feat: masonry layout component 구현
  package.json
  pnpm-lock.yaml
  src/components/common/MasonryLayout.tsx
  src/routes/my-liked-zzal/index.tsx
Labels: ✨ Feature

#94 [#92] Chore: router type 선언 및 devtools 추가
  package.json
  pnpm-lock.yaml
  src/App.tsx
  src/components/AdminReports/ReportsTableBody .tsx
  src/components/common/Header/index.tsx
  src/routes/__root.tsx
  src/routes/_layout-with-chat.tsx
  src/routes/admin/reports/$imageId/index.tsx
Labels: ⚙ Chore

#89 [#83] Feat: 좋아요한 짤 페이지에서 태그 추천 api 구현 및 적용
  src/apis/tag.ts
  src/apis/zzal.ts
  src/constants/api.ts
  src/hooks/api/tag/useGetTopTagsFromLiked.ts
  src/routes/_layout-with-chat/my-liked-zzals/route.lazy.tsx
  src/types/tag.dto.ts
Labels: ✨ Feature

#102 [#101] Chore: env 변수 추가
  .github/workflows/deploy.yml
Labels: ⚙ Chore

#93 [#91] Feat: 다운로드 짤 util 함수 구현
  src/utils/zzalUtils.ts
Labels: ✨ Feature

#86 [#81] Feat: 짤 이미지 삭제 api 연결 및 성공/삭제 시 동작 구현
  src/apis/zzal.ts
  src/components/ImageDetailModal/ImageMenuBar.tsx
  src/hooks/api/zzal/useDeleteMyZzal.ts
  src/routes/_layout-with-chat/index.tsx
Labels: ✨ Feature

#84 [#75] Feat: 이미지 상세 모달 layout 수정
  package.json
  pnpm-lock.yaml
  src/components/ImageDetailModal/ButtonWithIcon.tsx
  src/components/ImageDetailModal/TagNavigator.tsx
  src/components/ImageDetailModal/TagSlider.tsx
  src/components/ImageDetailModal/index.tsx
  src/components/common/modals/Modal.tsx
  src/types/tag.ts
  tailwind.config.js
Labels: ✨ Feature

#99 [#82] Modify: 채팅 레이아웃 v2 적용
  src/components/common/Chat/ChatSection.tsx
  src/components/common/Chat/Message.tsx
  src/components/common/Chat/index.tsx
  src/routes/_layout-with-chat.tsx
  tailwind.config.js
Labels: ✏️ Modify, 🎨 Style

#88 [#87] Feat: 짤 이미지 신고 확인 모달 UI 구현
  src/components/ImageDetailModal/ImageMenuBar.tsx
  src/components/ReportConfirmModal/index.tsx
  src/components/common/DeleteConfirmModal.tsx
  src/components/common/modals/ModalHeader.tsx
Labels: ✨ Feature

#96 [#79] Feat: 채팅 기능 연결
  package.json
  pnpm-lock.yaml
  src/components/common/Chat/ChatPeek.tsx
  src/components/common/Chat/ChatSendButton.tsx
  src/components/common/Chat/GreetMessage.tsx
  src/components/common/Chat/Message.tsx
  src/components/common/Chat/MessagePeek.tsx
  src/components/common/Chat/ZzalMessage.tsx
  src/components/common/Chat/index.tsx
  src/constants/chat.ts
  src/hooks/chat/useChat.ts
  src/sockjs-client.d.ts
  src/types/chat.dto.ts
Labels: ✨ Feature

#76 [#74] Feat: 짤 이미지 신고 api 연결 구현
  src/apis/report.ts
  src/components/ImageDetailModal/ImageMenuBar.tsx
  src/hooks/api/report/useDeleteReportedZzal.tsx
  src/hooks/api/zzal/usePostReportZzal.ts
  src/routes/admin/reports/$imageId/index.tsx
Labels: ✨ Feature

#106 [#105] Refactor: ImageDetailModal과 ImageMenuBar 병합
  src/components/ImageDetailModal/ImageMenuBar.tsx
  src/components/ImageDetailModal/index.tsx
Labels: 🔨 Refactor, 🏷️ Rename

#116 [#110] Feat: 로그아웃 기능 구현
  src/apis/auth.ts
  src/components/common/Header/DropdownMenu.tsx
  src/constants/auth.ts
  src/hooks/api/auth/useLogout.ts
Labels: ✨ Feature

#109 [#85] Feat: OAuth 로그인 기능 구현
  src/apis/core.ts
  src/components/LoginModal.tsx
  src/components/common/Header/DropdownMenu.tsx
  src/routes/_layout-with-chat/index.tsx
Labels: ✨ Feature

#107 [#80] Feat: 짤카드 레이아웃 변경, 복사 아이콘 추가 및 각각의 버튼 기능 구현
  src/apis/zzal.ts
  src/components/common/ZzalCard.tsx
  src/hooks/api/zzal/useAddImageLike.ts
  src/hooks/api/zzal/useRemoveImageLike.ts
  src/types/queryKey.ts
  src/types/zzal.dto.ts
  src/utils/copyZzal.ts
Labels: ✨ Feature

#118 [#112] Style: v3 layout 적용
  src/components/UploadZzal/ImageUpload.tsx
  src/components/common/Chat/index.tsx
  src/components/common/Header/DropdownMenu.tsx
  src/components/common/Header/index.tsx
  src/components/common/SearchTag/TagAutoComplete.tsx
  src/components/common/SearchTag/TagSearchForm.tsx
  src/routes/__root.tsx
  src/routes/_layout-with-chat.tsx
  src/routes/_layout-with-chat/my-liked-zzals/route.lazy.tsx
  src/routes/_layout-with-chat/my-uploaded-zzals/route.lazy.tsx
  src/routes/upload-zzal/index.tsx
Labels: 🎨 Style

#113 [#111] Feat: 태그 생성 API 구현
  src/apis/tag.ts
  src/hooks/api/tag/usePostTag.ts
  src/types/tag.dto.ts
  src/types/tag.ts
Labels: ✨ Feature

#108 [#69] Feat: 짤 상세 모달 get api 구현 및 적용
  src/apis/zzal.ts
  src/components/ImageDetailModal/ButtonWithIcon.tsx
  src/components/ImageDetailModal/TagSlider.tsx
  src/components/ImageDetailModal/index.tsx
  src/components/common/Spinner.tsx
  src/components/common/ZzalCard.tsx
  src/hooks/api/zzal/useGetZzalDetails.ts
  src/types/tag.ts
  src/types/zzal.dto.ts
  src/utils/copyZzal.ts
  src/utils/zzalUtils.ts
Labels: ✨ Feature

#120 [#114] Feat: 계정 삭제 페이지 layout 구현
  src/components/DeleteAccount/AccountDeletionNotice.tsx
  src/components/DeleteAccount/DeleteCompleted.tsx
  src/components/DeleteAccount/DeleteConfirm.tsx
  src/components/common/Header/DropdownMenu.tsx
  src/hooks/common/useFunnel.tsx
  src/routeTree.gen.ts
  src/routes/delete-account/index.tsx
Labels: ✨ Feature

#132 [#124] Style: pretendard default font로 적용
  index.html
  src/index.css
Labels: ✨ Feature

#68 [#46] Feat: 짤 업로드 api, 추천 태그 api 연결 및 Toast 구현
  src/apis/tag.ts
  src/apis/zzal.ts
  src/components/UploadZzal/ImageUpload.tsx
  src/components/UploadZzal/UploadGuide.tsx
  src/components/common/RecommendTag.tsx
  src/components/common/ZzalCard.tsx
  src/hooks/api/tag/useGetPopularTags.ts
  src/hooks/api/zzal/usePostUploadZzal.ts
  src/index.css
  src/routes/upload-zzal/index.tsx
  src/types/tag.dto.ts
  src/types/zzal.dto.ts
Labels: ✨ Feature

#104 [#103] Feat: 업로드한 짤 페이지에서 짤 get api 구현 및 적용
  src/apis/zzal.ts
  src/hooks/api/zzal/useGetMyUploadedZzals.ts
  src/routes/_layout-with-chat/my-uploaded-zzals/route.lazy.tsx
  src/types/zzal.dto.ts
Labels: ✨ Feature

#129 [#128] Feat: 유저 탈퇴 기능 구현
  src/apis/auth.ts
  src/components/DeleteAccount/DeleteCompleted.tsx
  src/components/DeleteAccount/DeleteConfirm.tsx
  src/components/common/Header/DropdownMenu.tsx
  src/hooks/api/auth/useDeleteUserWithdraw.ts
Labels: ✨ Feature

#145 [#144] Fix: pull request action 제거
  .github/workflows/deploy.yml
Labels: 🐞 Bugfix, ⚙ Chore

#149 [#147] Fix: 무한 스크롤 트리거를 위한 div 태그 보이지 않는 스타일 수정
  src/routes/_layout-with-chat.tsx
Labels: 🐞 Bugfix

#126 [#121] Modify: 자동완성 레이아웃 수정 및 키보드 이벤트 추가
  src/components/common/SearchTag/TagAutoComplete.tsx
  src/components/common/SearchTag/TagSearchForm.tsx
  src/components/common/TagBadge.tsx
  src/hooks/api/tag/useGetTags.ts
  src/routes/_layout-with-chat.tsx
  src/routes/_layout-with-chat/my-liked-zzals/route.lazy.tsx
  src/store/tag.ts
  tailwind.config.js
Labels: ✨ Feature, ✏️ Modify

#130 [#127] Feat: 사용된 태그 api 구현 및 적용
  src/apis/tag.ts
  src/components/common/SearchTag/TagAutoComplete.tsx
  src/components/common/SearchTag/TagSearchForm.tsx
  src/hooks/api/tag/usePostTag.ts
  src/hooks/api/tag/usePostUsedTag.ts
  src/types/tag.dto.ts
Labels: ✨ Feature

#137 [#133] Feat: 짤 신고 시 BE 커스텀 error code에 따라 구분된 신고 Toast 메시지 출력
  src/components/ImageDetailModal/index.tsx
Labels: ✨ Feature

#157 [#154] Refactor: 짤카드 리팩토링
  src/components/common/Chat/MessagePreview.tsx
  src/components/common/Chat/ZzalMessage.tsx
  src/components/common/ZzalCard.tsx
  src/routes/_layout-with-chat/my-liked-zzals/route.lazy.tsx
  src/routes/_layout-with-chat/my-uploaded-zzals/route.lazy.tsx
  src/routes/admin/reports/$imageId/index.tsx
  src/types/zzal.dto.ts
Labels: 🔨 Refactor

#159 [#97] Feat: 좋아요한 짤, 업로드한 짤 필터링 구현
  src/apis/zzal.ts
  src/hooks/api/zzal/useGetMyLikedZzals.ts
  src/hooks/api/zzal/useGetMyUploadedZzals.ts
  src/types/zzal.dto.ts
Labels: ✨ Feature

#152 [#151] Feat: TagSlider 공통컴포넌트화
  src/components/ImageDetailModal/index.tsx
  src/components/common/SearchTag/TagAutoComplete.tsx
  src/components/common/SearchTag/TagSearchForm.tsx
  src/components/common/TagSlider.tsx
  src/hooks/api/zzal/useGetZzalDetails.ts
  src/utils/sleep.ts
Labels: ✨ Feature

#158 [#153] Feat: 사용자 정보 header에 반영
  src/apis/auth.ts
  src/components/DeleteAccount/DeleteCompleted.tsx
  src/components/common/Header/DropdownMenu.tsx
  src/components/common/Header/index.tsx
  src/hooks/api/auth/useGetUserInformation.ts
  src/store/user.ts
  src/types/user.dto.ts
  src/types/user.ts
Labels: ✨ Feature

#166 [#163] Feat: 홈 페이지 구현
  src/apis/tag.ts
  src/apis/zzal.ts
  src/hooks/api/tag/useGetTopTagsFromHome.ts
  src/hooks/api/zzal/useGetHomeZzals.ts
  src/routeTree.gen.ts
  src/routes/_layout-with-chat/index.route.lazy.tsx
  src/routes/_layout-with-chat/index.route.tsx
  src/types/tag.dto.ts
  src/types/zzal.dto.ts
Labels: ✨ Feature

#165 [#164] Feat: 짤카드와 짤 상세 모달 연결
  src/components/ImageDetailModal/index.tsx
  src/components/common/ZzalCard.tsx
Labels: ✨ Feature

#135 [#125] Feat: 프로젝트 메타데이터 설정
  index.html
  package.json
  pnpm-lock.yaml
  public/favicon-32x32.png
  public/thumbnail.jpg
  src/App.tsx
  src/routes/_layout-with-chat/index.route.tsx
  src/routes/_layout-with-chat/my-liked-zzals/route.tsx
  src/routes/_layout-with-chat/my-uploaded-zzals/route.tsx
  src/routes/admin/reports/index.tsx
  src/routes/delete-account/index.tsx
  src/routes/upload-zzal/index.tsx
Labels: ✨ Feature

#162 [#160] Feat: 업로드한 짤 페이지에 짤 삭제 버튼 추가
  src/hooks/api/zzal/useDeleteMyZzal.ts
  src/routes/_layout-with-chat/my-uploaded-zzals/route.lazy.tsx
Labels: ✨ Feature

#134 [#115] Feat: google analytics 연동
  index.html
  package.json
  pnpm-lock.yaml
  src/components/AdminReports/ReportsTableBody .tsx
  src/components/DeleteAccount/DeleteCompleted.tsx
  src/components/ImageDetailModal/index.tsx
  src/components/common/Header/DropdownMenu.tsx
  src/components/common/Header/ThemeToggle.tsx
  src/components/common/Header/index.tsx
  src/components/common/ZzalCard.tsx
  src/routes/__root.tsx
  src/routes/_layout-with-chat.tsx
  src/routes/admin/reports/$imageId/index.tsx
  src/utils/zzalUtils.ts
Labels: ✨ Feature

#155 [#150] Feat: Protected Routing
  src/App.tsx
  src/apis/auth.ts
  src/components/Auth/index.tsx
  src/components/common/Header/index.tsx
  src/components/common/modals/ModalHeader.tsx
  src/constants/auth.ts
  src/hooks/auth/useAuthContext.ts
  src/routeTree.gen.ts
  src/routes/__root.tsx
  src/routes/_authentication.tsx
  src/routes/_authentication/admin/reports/$imageId/index.tsx
  src/routes/_authentication/admin/reports/AdminReports.pendingComponent.tsx
  src/routes/_authentication/admin/reports/index.tsx
  src/routes/_authentication/delete-account/index.tsx
  src/routes/_authentication/upload-zzal/index.tsx
  src/routes/_layout-with-chat.tsx
  src/routes/_layout-with-chat/index.route.tsx
Labels: ✨ Feature

#170 [#167] Fix: 액세스 토큰 null 오류 및 로그아웃 시 새로고침 수정
  src/apis/core.ts
  src/hooks/api/auth/useLogout.ts
Labels: 🐞 Bugfix

#168 [#136] Feat: 짤 상세 모달에서 삭제 버튼 제거
  src/components/ImageDetailModal/ButtonWithIcon.tsx
  src/components/ImageDetailModal/index.tsx
  src/components/common/DeleteConfirmModal.tsx
  src/routes/_authentication/admin/reports/$imageId/index.tsx
  src/routes/_layout-with-chat/my-uploaded-zzals/route.lazy.tsx
Labels: ✨ Feature

#161 [#122] Feat: 채팅 v2 기능 연결
  src/apis/chat.ts
  src/components/common/Chat/ZzalMessage.tsx
  src/components/common/Chat/index.tsx
  src/hooks/api/chat/useGetChat.ts
  src/hooks/chat/useChat.ts
  src/routes/_layout-with-chat.tsx
  src/types/chat.dto.ts
  src/types/chat.ts
Labels: ✨ Feature

#176 [#173] Feat: sentry로 에러 로깅
  .github/workflows/deploy.yml
  package.json
  pnpm-lock.yaml
  src/apis/core.ts
  src/hooks/api/auth/useDeleteUserWithdraw.ts
  src/hooks/api/auth/useLogout.ts
  src/hooks/api/tag/usePostTag.ts
  src/hooks/api/zzal/useAddImageLike.ts
  src/hooks/api/zzal/useRemoveImageLike.ts
  src/main.tsx
  src/utils/zzalUtils.ts
Labels: ✨ Feature

#179 [#178] Fix: 언마운트 후 재마운트 시 infiniteQuery 버그 fix
  src/hooks/api/zzal/useGetHomeZzals.ts
  src/hooks/api/zzal/useGetMyLikedZzals.ts
  src/hooks/api/zzal/useGetMyUploadedZzals.ts
Labels: 🐞 Bugfix

#174 [#171] Fix: 낙관적 업데이트 버그 수정 및 짤카드 margin 추가
  src/components/common/ZzalCard.tsx
  src/hooks/api/zzal/useAddImageLike.ts
  src/hooks/api/zzal/useGetHomeZzals.ts
  src/hooks/api/zzal/useRemoveImageLike.ts
  src/routes/_layout-with-chat/index.route.lazy.tsx
  src/routes/_layout-with-chat/my-liked-zzals/route.lazy.tsx
  src/routes/_layout-with-chat/my-uploaded-zzals/route.lazy.tsx
  src/types/queryKey.ts
Labels: 🐞 Bugfix

#177 [#131] Feat: image detail modal에 좋아요 기능 연결
  src/components/ImageDetailModal/index.tsx
  src/hooks/api/zzal/useAddImageDetailLike.ts
  src/hooks/api/zzal/useRemoveImageDetailLike.ts
Labels: ✨ Feature

#190 [#186] Style: 자동완성 검색창 다크 모드 적용
  src/components/ImageDetailModal/index.tsx
  src/components/UploadZzal/UploadTagAutoComplete.tsx
  src/components/UploadZzal/UploadTagBadge.tsx
  src/components/common/SearchTag/TagAutoComplete.tsx
  src/components/common/SearchTag/TagSearchForm.tsx
  src/components/common/TagBadge.tsx
  tailwind.config.js
Labels: 🎨 Style

#172 [#146] Feat: 검색 결과가 없는 경우 보여줄 컴포넌트 적용
  src/components/common/NoSearchResults.tsx
  src/routes/_layout-with-chat/my-liked-zzals/route.lazy.tsx
  src/routes/_layout-with-chat/my-uploaded-zzals/route.lazy.tsx
Labels: ✨ Feature

#188 [#187] Fix: pathname 변경시 선택된 태그 초기화
  src/routes/_layout-with-chat.tsx
Labels: 🐞 Bugfix

#196 [#194] Style: 다크모드 적용 및 스타일 수정
  src/components/LoginModal.tsx
  src/components/common/ZzalCard.tsx
  src/components/common/modals/Modal.tsx
  src/components/common/modals/ModalHeader.tsx
  src/routes/_layout-with-chat/my-uploaded-zzals/route.lazy.tsx
Labels: 🎨 Style

#199 [#198] Feat: 업로드 이미지 파일을 JPG로 변환하는 기능 구현
  src/routes/_authentication/upload-zzal/index.tsx
  src/utils/convertFileToJpg.ts
  src/utils/zzalUtils.ts
Labels: ✨ Feature

#205 [#204] Feat: 짤 상세 모달에 보내기 기능 추가
  src/components/ImageDetailModal/index.tsx
  src/store/chat.ts
Labels: ✨ Feature

#185 [#184] Fix: TagSlider 화살표 버튼 렌더 버그 fix
  src/components/common/SearchTag/TagSearchForm.tsx
  src/components/common/TagSlider.tsx
Labels: 🐞 Bugfix

#191 [#189] Fix: 짤 업로드시 query key invalidate
  src/hooks/api/zzal/usePostUploadZzal.ts
Labels: 🐞 Bugfix

#193 [#192] Fix: tag 입력시 input 초기화
  src/components/common/SearchTag/TagAutoComplete.tsx
  src/components/common/SearchTag/TagSearchForm.tsx
Labels: 🐞 Bugfix

#211 [#209] Fix: 좋아요 api훅 버그 수정
  src/components/ImageDetailModal/index.tsx
  src/components/common/ZzalCard.tsx
  src/hooks/api/zzal/useAddImageDetailLike.ts
  src/hooks/api/zzal/useAddImageLike.ts
  src/hooks/api/zzal/useRemoveImageDetailLike.ts
  src/hooks/api/zzal/useRemoveImageLike.ts
  src/routes/_layout-with-chat/my-liked-zzals/route.lazy.tsx
Labels: 🐞 Bugfix

#212 [#210] Modify: 채팅 인사 메세지 정책 업데이트
  src/apis/chat.ts
  src/components/common/Chat/GreetMessage.tsx
  src/components/common/Chat/index.tsx
  src/constants/chat.ts
  src/hooks/api/chat/usePostChatNickname.ts
  src/hooks/chat/useChat.ts
  src/types/chat.dto.ts
  src/types/chat.ts
Labels: ✏️ Modify

#201 [#200] Modify: 헤더의 admin버튼 드롭다운메뉴 버튼으로 변경
  src/components/common/Header/DropdownMenu.tsx
  src/components/common/Header/index.tsx
Labels: ✏️ Modify

#207 [#206] Feat: 짤 상세모달에 비회원 신고하기 제한
  src/components/ImageDetailModal/index.tsx
  src/components/common/ZzalCard.tsx
Labels: ✨ Feature

#203 [#202] Fix: 리프레시 토큰 만료 시, 로그아웃 됨과 동시에 루트로 이동되지 않는 버그 수정
  src/apis/auth.ts
  src/apis/core.ts
Labels: 🐞 Bugfix

#208 [#197] Style: layout without chat 하위 페이지 UI 및 레이아웃 수정
  package.json
  pnpm-lock.yaml
  src/components/common/Chat/index.tsx
  src/components/common/Header/index.tsx
  src/routes/__root.tsx
  src/routes/_authentication.tsx
  src/routes/_authentication/upload-zzal/index.tsx
  src/routes/_layout-with-chat.tsx
  src/routes/_layout-with-chat/my-uploaded-zzals/route.lazy.tsx
  src/store/scroll.ts
Labels: 🎨 Style

#182 [#181] Modify : 짤 업로드 페이지에 TagSlider 컴포넌트 적용
  src/components/UploadZzal/UploadTagAutoComplete.tsx
  src/components/UploadZzal/UploadTagBadge.tsx
  src/components/UploadZzal/UploadTagSearchForm.tsx
  src/components/common/SearchTag/TagAutoComplete.tsx
  src/components/common/TagBadge.tsx
  src/routes/_authentication/upload-zzal/index.tsx
  src/store/tag.ts
Labels: ✏️ Modify

#180 [#169] Style: 짤 업로드 페이지 UI 수정
  src/components/UploadZzal/ImageUpload.tsx
  src/components/UploadZzal/UploadGuide.tsx
  src/components/UploadZzal/UploadTagAutoComplete.tsx
  src/components/UploadZzal/UploadTagBadge.tsx
  src/components/UploadZzal/UploadTagSearchForm.tsx
  src/components/common/SearchTag/TagAutoComplete.tsx
  src/components/common/TagBadge.tsx
  src/routes/_authentication/upload-zzal/index.tsx
  src/store/tag.ts
Labels: 🎨 Style

#214 [#213] Fix: 추천 태그 없는 경우 0 노출 이슈 해결
  src/components/common/SearchTag/TagSearchForm.tsx
Labels: 🐞 Bugfix

#195 [#183] Style: chat with layout 하위 페이지 UI 및 레이아웃 수정
  package.json
  pnpm-lock.yaml
  src/components/common/Chat/index.tsx
  src/components/common/Header/index.tsx
  src/components/common/SearchTag/TagAutoComplete.tsx
  src/components/common/SearchTag/TagSearchForm.tsx
  src/components/common/TagBadge.tsx
  src/components/common/TagSlider.tsx
  src/routes/__root.tsx
  src/routes/_authentication.tsx
  src/routes/_authentication/upload-zzal/index.tsx
  src/routes/_layout-with-chat.tsx
  src/routes/_layout-with-chat/my-uploaded-zzals/route.lazy.tsx
  src/store/scroll.ts
Labels: 🎨 Style

#216 [#215] Fix: 다크모드에서 업로드 페이지 배경색 변경 및 자동완성 태그 호버 할 때 텍스트 색상 변경
  src/components/UploadZzal/UploadTagAutoComplete.tsx
  src/components/common/SearchTag/TagAutoComplete.tsx
  src/routes/_authentication/upload-zzal/index.tsx
Labels: 🎨 Style

#223 [#219] Fix: 업로드한 짤페이지 짤카드 레이아웃 깨짐 및 페이지 무한스크롤 에러 해결
  src/components/common/ZzalCard.tsx
  src/routes/_layout-with-chat/my-liked-zzals/route.lazy.tsx
  src/routes/_layout-with-chat/my-uploaded-zzals/route.lazy.tsx
Labels: 🐞 Bugfix

#221 [#218] Style: shadow 색상 토큰 생성 및 적용
  src/components/common/Header/DropdownMenu.tsx
  src/components/common/SearchTag/TagAutoComplete.tsx
  src/components/common/SearchTag/TagSearchForm.tsx
  src/routes/__root.tsx
  src/routes/_layout-with-chat.tsx
  tailwind.config.js
Labels: 🎨 Style

#224 [#220 ] Fix: useChat의 useInfiniteQuery hasNextPage 판별 로직 추가
  src/hooks/api/chat/useGetChat.ts
Labels: 🐞 Bugfix

#225 [#217] Fix: UploadSearchForm 이슈 수정
  src/components/UploadZzal/UploadTagAutoComplete.tsx
  src/components/UploadZzal/UploadTagSearchForm.tsx
Labels: 🐞 Bugfix

#227 [#226] Fix: 좋아요 또는 좋아요 취소 시 좋아요 페이지 캐싱 무효화
  src/App.tsx
  src/hooks/api/zzal/useAddImageLike.ts
  src/hooks/api/zzal/useGetHomeZzals.ts
  src/hooks/api/zzal/useGetMyLikedZzals.ts
  src/hooks/api/zzal/useGetMyUploadedZzals.ts
  src/hooks/api/zzal/useRemoveImageLike.ts
  src/routes/_layout-with-chat.tsx
Labels: 🐞 Bugfix

#229 [#228] Style: 관리자 페이지 레이아웃 수정
  src/routes/_authentication/admin/reports/$imageId/index.tsx
  src/routes/_authentication/admin/reports/index.tsx
Labels: ✏️ Modify, 🎨 Style

#230 [#222] Style: 업로드 페이지 반응형 레이아웃 수정
  src/components/UploadZzal/ImageUpload.tsx
  src/routes/__root.tsx
  src/routes/_authentication/upload-zzal/index.tsx
Labels: 🎨 Style

#232 [#231] Fix: 서버 리프레시 토큰 관련 에러 핸들링 및 로그아웃 api에 누락된 header 추가
  src/apis/auth.ts
  src/apis/core.ts
  src/hooks/api/auth/useLogout.ts
Labels: 🐞 Bugfix, 🔨 Refactor

#236 [#233] Fix: TagSearchForm 배포 환경에서 깨짐 현상 fix
  src/components/common/SearchTag/TagSearchForm.tsx
Labels: 🐞 Bugfix

#237 [#235] Fix: TanStack Router devtools 배포 환경에서 보이는 버그 해결
  src/routes/__root.tsx
Labels: 🐞 Bugfix

#238 [#234] Fix: 업로드 페이지 레이아웃 짤림 버그 해결
  src/components/UploadZzal/UploadTagAutoComplete.tsx
  src/components/common/SearchTag/TagAutoComplete.tsx
  src/routes/__root.tsx
  src/routes/_authentication/upload-zzal/index.tsx
Labels: 🐞 Bugfix, ✏️ Modify
